### ISSUE TITLE
Imaginary error function (erfi)

### ISSUE THREAD

**Issue by nilgoyette** [stainless-steel/special#10]
Hi all. I'm trying to port a Python application to Rust. It uses

    scipy.special.erfi(sk)  # NOTE: sk is a double, not a complex number

I understand that this crate offers the error, complementary and inverse functions. I searched if it's possible to define erfi with what's available here. It seems that 

    erfi(z) = -i erf(iz)

but erf is only defined for f32 and f64 so I can't call it with the complex number `iz`.

SciPy uses the Faddeeva lib for [erfi(f64)](https://github.com/scipy/scipy/blob/8a64c938ddf1ae4c02a08d2c5e38daeb8d061d38/scipy/special/Faddeeva.cc#L278). It's not too complex but it calls an ugly [switch](https://github.com/scipy/scipy/blob/8a64c938ddf1ae4c02a08d2c5e38daeb8d061d38/scipy/special/Faddeeva.cc#L1318) :( There's also the [truncnorm crate](https://crates.io/crates/truncnorm) that offers the complementary erfi, but they also use Faddeeva.

So, before I start porting this function to Rust, do you know if there's an easy way to have the erfi(f32/f64) function in Rust by using your crate?

**Comment by IvanUkhov** [comment]
Hello, an interesting question. If there is no clever mathematical trick to re-express via the ones available, I assume one would have to write a proper implementation of the error function (right now it is simply taken from `libm`) so it can handle complex numbers. Perhaps this could be the reference:

https://www.boost.org/doc/libs/1_49_0/boost/math/special_functions/erf.hpp

**Comment by nilgoyette** [comment]
Hi Ivan, thanks for the answer. I simply used FFI to the Faddeeva package. I always prefer having Rust code, but it took me 30 minutes instead of several hours of porting and testing.
