### ISSUE TITLE
Add Bessel functions

### ISSUE THREAD

**Issue by BaxterEaves** [stainless-steel/special#7]
Hi,

I've implemented modified Bessel functions I<sub>0</sub> and I<sub>1</sub> for the [rv crate](https://crates.io/crates/rv), but I think that they would be more useful here. Are you open to a PR for a `Bessel` trait? With what I have right now it would look something like this:

```rust
trait Bessel where Self: Sized {
    /// Modified Bessel function of order 0
    fn i0(self) -> Self;
    /// Modified Bessel function of order 1
    fn i1(self) -> Self;
}
```

I'm open to adding more Bessel things if you feel this isn't complete enough for a new trait.

**Comment by IvanUkhov** [comment]
Thanks! It’s certainly of interest.

What method is used for computing them? Can you please motivate why these particular orders are important? Are there any difficulties with computing Bessel functions of arbitrary orders?

**Comment by BaxterEaves** [comment]
The I0 and I1 modified bessel functions are important for computing the [VonMises distribution](https://en.wikipedia.org/wiki/Von_Mises_distribution) PDF and variance. In general, bessel functions show up in physics a lot. 

There is no problem computing the modified bessel functions for arbitrary order (though the code is a bit of a beast), but the i0 and i1 functions i have are faster for their orders than the general algorithm.

As for the method, I ported the Cephes code packaged with Scipy.

**Comment by IvanUkhov** [comment]
All right, given the way they will be most likely invoked, do you think it makes sense to include `bessel` in their names?

```rust
use special::Bessel;
let y = x.bessel_i0();
```
